# Generated by Django 6.0.6 on 2026-06-06 04:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Pengupul')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='No. Telepon')),
                ('address', models.TextField(blank=True, verbose_name='Alamat')),
                ('id_card_number', models.CharField(blank=True, max_length=30, verbose_name='No. KTP')),
                ('join_date', models.DateField(auto_now_add=True, verbose_name='Tanggal Bergabung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
            ],
            options={
                'verbose_name': 'Pengupul',
                'verbose_name_plural': 'Data Pengupul',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Jenis Sampah')),
                ('category', models.CharField(choices=[('plastik', 'Plastik'), ('logam', 'Logam'), ('kertas', 'Kertas'), ('kaca', 'Kaca'), ('elektronik', 'Elektronik'), ('tekstil', 'Tekstil'), ('organik', 'Organik'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20, verbose_name='Kategori')),
                ('purchase_price_per_kg', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Harga Beli per Kg (Rp)')),
                ('selling_price_per_kg', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Harga Jual per Kg (Rp)')),
                ('unit', models.CharField(default='kg', max_length=20, verbose_name='Satuan')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Jenis Sampah',
                'verbose_name_plural': 'Data Jenis Sampah',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OperationalCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transport', 'Transportasi'), ('rent', 'Sewa Tempat'), ('salary', 'Gaji Karyawan'), ('equipment', 'Peralatan'), ('utility', 'Utilitas (Listrik/Air)'), ('maintenance', 'Perawatan'), ('other', 'Lainnya')], max_length=20, verbose_name='Kategori')),
                ('description', models.CharField(max_length=300, verbose_name='Deskripsi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Jumlah (Rp)')),
                ('date', models.DateField(verbose_name='Tanggal')),
                ('receipt_number', models.CharField(blank=True, max_length=100, verbose_name='No. Kwitansi')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
            ],
            options={
                'verbose_name': 'Biaya Operasional',
                'verbose_name_plural': 'Data Biaya Operasional',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WasteTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'Pembelian (Masuk)'), ('out', 'Penjualan (Keluar)')], max_length=3, verbose_name='Jenis Transaksi')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Berat (Kg)')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga per Kg (Rp)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total Harga (Rp)')),
                ('date', models.DateTimeField(verbose_name='Tanggal Transaksi')),
                ('factory_name', models.CharField(blank=True, max_length=200, verbose_name='Nama Pabrik/Pembeli')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='waste_mgmt.collector', verbose_name='Pengupul')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='waste_mgmt.wastetype', verbose_name='Jenis Sampah')),
            ],
            options={
                'verbose_name': 'Transaksi Sampah',
                'verbose_name_plural': 'Data Transaksi Sampah',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FactorySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_name', models.CharField(max_length=200, verbose_name='Nama Pabrik')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Berat Dijual (Kg)')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga Jual per Kg (Rp)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total Penjualan (Rp)')),
                ('date', models.DateField(verbose_name='Tanggal Penjualan')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Biaya Pengiriman (Rp)')),
                ('payment_status', models.CharField(choices=[('pending', 'Belum Dibayar'), ('paid', 'Sudah Dibayar'), ('partial', 'Sebagian')], default='pending', max_length=20, verbose_name='Status Pembayaran')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factory_sales', to='waste_mgmt.wastetype', verbose_name='Jenis Sampah')),
            ],
            options={
                'verbose_name': 'Penjualan ke Pabrik',
                'verbose_name_plural': 'Data Penjualan ke Pabrik',
                'ordering': ['-date'],
            },
        ),
    ]
